import type { LucideIcon } from "lucide-react";
import type { ReactNode } from "react";
import { Sparkles } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

interface AnalysisSectionProps {
  icon: LucideIcon;
  title: string;
  children: ReactNode;
}

/**
 * Shared Card shell for every AI-generated analysis block (Purpose,
 * Architecture, Tech Stack, How to Run, Interview Questions,
 * Improvements). Centralizing this means changing the header layout
 * or the "AI generated" indicator updates every section at once
 * instead of six separate places.
 */
export function AnalysisSection({ icon: Icon, title, children }: AnalysisSectionProps) {
  return (
    <Card>
      <CardHeader className="flex-row items-center justify-between space-y-0">
        <div className="flex items-center gap-2">
          <Icon className="h-4 w-4 text-primary" />
          <CardTitle>{title}</CardTitle>
        </div>

        <Tooltip>
          <TooltipTrigger asChild>
            <Badge variant="accent" className="gap-1 cursor-default">
              <Sparkles className="h-3 w-3" />
              AI
            </Badge>
          </TooltipTrigger>
          <TooltipContent>Generated by Gemini from repo metadata + README</TooltipContent>
        </Tooltip>
      </CardHeader>
      <CardContent>{children}</CardContent>
    </Card>
  );
}
